[build]
  base = "/"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://13.61.21.193:3002/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
